### ISSUE TITLE
Notes disappear instead of being restored

### ISSUE THREAD

**Issue by motatuc** [BijoySingh/Material-Notes-Android-App#11]
Hello

Thanks for this nice application. Well made as well. It seems to have at least one bug though (or maybe I just do not understand that feature). If you delete a note and go to trash and then choose to restore it, the note is gone.

Btw: Would it be possible to make the note fields smaller in height? It seems really big to me.

Anyways, thats just cosmetics. But thanks for looking into the bug.

**Comment by BijoySingh** [comment]
Hi, this was fixed in c19b69e6bdb7cd207bd47a72c1fd5045f74e4831
An update to the play store has already fixed it. I'll be creating a new release for F-Droid to resolve that there too.
