### ISSUE TITLE
Change of Icon Title

### ISSUE THREAD

**Issue by skx7** [BijoySingh/Material-Notes-Android-App#13]
First of all thanks for a very nice little app! A minor request though, I like the name Material Notes but would it be possible to shorten the name under the icon to just Notes or Motes (from Material Notes). The title is too long too be fully shown under the nice material icon ;) thanks

**Comment by BijoySingh** [comment]
Hi! That's the best Issue I got so far :) 
Probably not Motes though ... 😆 
I think you are right, I will change it to "Notes"

**Comment by BijoySingh** [comment]
The app is now called Scarlet on Play Store :)
