### ISSUE TITLE
[Feature request] Password protect notes

### ISSUE THREAD

**Issue by simon-v** [BijoySingh/Material-Notes-Android-App#16]
The ability to lock a note behind a password is a nice feature to have. Potentially, a new category, "Locked notes" would need to be added.

**Comment by BijoySingh** [comment]
@simon-v cd3e9e97592b746475ec55d8242365b5da9adaa4 added this feature. 
I will consider this as a request for a new note category - Locked Notes.

**Comment by BijoySingh** [comment]
Added in a1e2b46551d202578c06463c8b121476b02580e1
