### ISSUE TITLE
three-dots-menu bugs

### ISSUE THREAD

**Issue by x2k13** [BijoySingh/Material-Notes-Android-App#18]
When you click on a note's three-dots-menu in portrait mode, an additional menu appears at the bottom of the screen, but the menu is not adapting to the screen width, making the items of the last collumn unusable. When you try to rotate the device to landscape mode to see all the menu entries, the app crashes. Same for opening the app in landscape mode and then rotating to portrait mode.

**Comment by BijoySingh** [comment]
Thanks! The crash is reproducable. 
Can you add a screenshot for the last column not showing?

**Comment by x2k13** [comment]
Sure, here you go. Maybe the menu is cut off due to the text under the menu icons being to long?
Thinking about it, the "being cut-off" issue could be fixed automagically by changing the text like this:

Bearbeiten Hinweis > Bearbeiten
Mark Favorit > zu Favoriten
Archivnotiz > Archivieren
Senden Sie Anmerkung > Teilen
Kopie beachten > Kopieren
Ab in den Müll > Löschen

![screenshot_20171213-084629](https://user-images.githubusercontent.com/13673423/33929812-18dddc28-dfeb-11e7-8f40-dc4d36c8a616.png)

**Comment by BijoySingh** [comment]
Resolved in 94f311d2002b290e64ef9454e1c2d85fecd029a3, dc6c05e970a298f95357cdfb353de2d16a5a5e6e
