### ISSUE TITLE
It's impossible to create a new note (v3.7.0)

### ISSUE THREAD

**Issue by Jiack214** [BijoySingh/Material-Notes-Android-App#19]
Since v3.7, "Add a quick note" opens last note created instead a new one.

It's an important bug because currently it's impossible to create a new  note.

**Comment by BijoySingh** [comment]
Hey! Thanks! Fixed it right away. Update on play store is published. And Fdroid release created.
Fixed in 1a79de5eb5206ebbcbe6a50b63aba4f71dee2ce8
