### ISSUE TITLE
Dropbox Sync?

### ISSUE THREAD

**Issue by DavidXochipilli** [BijoySingh/Material-Notes-Android-App#2]
What do you think of the possiblity to sync notes with [Dropbox](https://www.dropbox.com/developers)?

**Comment by TGNYC** [comment]
I agree. I think that a notes app needs to have an option to sync to Dropbox or Google Drive or maybe a personally hosted server application.

**Comment by patschi** [comment]
I also would like to have any integration with OwnCloud/Nextcloud using WebDAV. CalDAV or using 3rd party app like https://play.google.com/store/apps/details?id=at.bitfire.davdroid, also open source, for synchronization.

**Comment by BijoySingh** [comment]
Closing this as will be managing via the other issue. #3
