### ISSUE TITLE
Export/Import function bugs

### ISSUE THREAD

**Issue by x2k13** [BijoySingh/Material-Notes-Android-App#21]
When exporting/importing a backup of our notes, even the deleted ones (!) get backuped and restored.

Steps to reproduce:

- Add several notes
- Delete some of them
- Export BACKUP.txt
- Uninstall App or delete App's data
- Install App (or just fire it up in case you only deleted the app data)
- Grant permissions and import BACKUP.txt

Result: All our notes are back, the formerly deleted ones as well.

**Comment by BijoySingh** [comment]
Ah, thanks for flagging this and adding the repro steps.

**Comment by x2k13** [comment]
Thanks for fixing stuff so quickly, keep up the good work!

**Comment by x2k13** [comment]
I guess the issue is fixed in 3.7.6. When moving notes to trash, then deleting them in trash, doing the steps in the first post, deleted notes don't get backuped/imported again. 🙂 Closing this, thanks!
