### ISSUE TITLE
Nubmers are cut off in ordered lists

### ISSUE THREAD

**Issue by KrazyCavin** [BijoySingh/Material-Notes-Android-App#22]
Create a note and write down the list
```
1. Number one
2. Number two
3. No.
```
![screenshot_20171218-225550__01](https://user-images.githubusercontent.com/14293537/34130230-60c3139a-e447-11e7-808c-22c75326a680.jpg)

Save the note and open it again. The numbers are half cut off, like:
![screenshot_20171218-225600__01](https://user-images.githubusercontent.com/14293537/34130239-6a3ce27a-e447-11e7-9ec9-8fa0f8d1cb51.jpg)

**Comment by BijoySingh** [comment]
Fixed in c297db8b4c2ebbbf1fcdef6c233846e0d711b837
