### ISSUE TITLE
Issue with PIN Lock

### ISSUE THREAD

**Issue by iknownothingaboutcomputers** [BijoySingh/Material-Notes-Android-App#25]
PIN lock doesn't work at all.

Android 5.1

Version 3.5.0. F-Droid

**Comment by BijoySingh** [comment]
Wait.. what? I use it all the time. Just to clarify you don't lock the app, you lock a note. 

Can you clarify, else I will have to close this for being ambiguous.

**Comment by iknownothingaboutcomputers** [comment]
@BijoySingh Oh, you're right. It's for locking notes, not the app. Terribly sorry, man.
