### ISSUE TITLE
About Checked Items

### ISSUE THREAD

**Issue by iknownothingaboutcomputers** [BijoySingh/Material-Notes-Android-App#26]
Please automatically move checked items to the bottom of the list. Ditto when you see the list on the main page of the app.

Version 3.5.0. F-Droid

**Comment by BijoySingh** [comment]
I was thinking about it. And I don't know if that's a good idea. Unlike Google Keep this is not just a list app, it may not be ideal to move checked content to move to bottom, as that will spoil the Rich text experience.

However, I will add logic to move it to the bottom of a continuous list of check boxes. And that setting can be disabled.

**Comment by BijoySingh** [comment]
Available since v4.4.1
