### ISSUE TITLE
Black Theme

### ISSUE THREAD

**Issue by iknownothingaboutcomputers** [BijoySingh/Material-Notes-Android-App#27]
Thanks for the dark theme but a pure black theme would be awesome!

Version 3.5.0. F-Droid

**Comment by BijoySingh** [comment]
I doubt I will get there anytime soon. The app is very deeply integrated for 2 themes only. 
Will leave this one as a feature request for the future :)

**Comment by iknownothingaboutcomputers** [comment]
@BijoySingh Whenever you have the time for it, man. No hurry, no worry. :)

**Comment by BijoySingh** [comment]
I have added it, but in the pro app on the play store only. Sorry i kinda had to in account for the fact the app is getting too popular for my ability to pay for the server costs.
