### ISSUE TITLE
About the Time and Date Information Shown on the Card

### ISSUE THREAD

**Issue by iknownothingaboutcomputers** [BijoySingh/Material-Notes-Android-App#28]
Please give the option to disable the time and date of creation of a note so that it doesn't appear at the bottom of a card in both grid and list layout. Clutters the note, IMO.

Version 3.5.0. F-Droid

**Comment by BijoySingh** [comment]
Yes. Again the latest release will fix this. 
Will leave it open till I create a new v3.7.6 release for FDroid.
