### ISSUE TITLE
File attachment

### ISSUE THREAD

**Issue by 0azizi0** [BijoySingh/Material-Notes-Android-App#30]
Can you add the abilty to  attach files (images, documents, etc), it's the the only feature i'm missing and very useful, thanks for the great app.

**Comment by 0azizi0** [comment]
Sorry my bad, i never noticed the other issue #17 but, please consider it a high priority, thanks.

**Comment by BijoySingh** [comment]
Closing this as it's the duplicate.. Will update details there. 
Also, while it is important, things like Cloud support, sorting/pinning, etc are higher pri.
