### ISSUE TITLE
Feature: Options to change font-size

### ISSUE THREAD

**Issue by Wolfram-Wolf** [BijoySingh/Material-Notes-Android-App#31]
Long lines wrap to the next line making slightly long-line notes scatter. Could be fixed by allowing custom font-sizes.

**Comment by BijoySingh** [comment]
This is unlikely something I will get into. It is both difficult to add, and adds not much value.
Infact, the key idea behind the app is to keep it simple yet powerful, this will only complicate things. Maybe one day I come back to this, for now it's a wontfix.
