### ISSUE TITLE
Swiftkey Keyboard not giving all functionalities with app

### ISSUE THREAD

**Issue by iamjaspreetsingh** [BijoySingh/Material-Notes-Android-App#33]
When using Swiftkey keyboard app (that comes by default in many mobiles) while adding notes, the keyboard is not working fine.
The suggestions are not available for words and even the words cannot be typed from swiping letter to letter.
These features of keyboard works well with all other apps.

**Comment by iamjaspreetsingh** [comment]
The error log of the issue is given in following link 
https://pastebin.com/raw/KaWMgEr7

**Comment by BijoySingh** [comment]
Resolved. Fix will be rolling out with v3.7.9
