### ISSUE TITLE
[Request] Folders

### ISSUE THREAD

**Issue by Crazy-Unicooorn** [BijoySingh/Material-Notes-Android-App#34]
Hi ! Thank you for developing that good app :)
I would be very happy if we have the functionality of sorting notes in different folders :) So that I can have a folder where all my "To Do notes" are, and an other where all my "thoughts notes" are for example ^^

Thank you and have a good day :)

**Comment by Wolfram-Wolf** [comment]
Try making tick-lists for TODOs and notes for everything else. You can also try color coding them. [You can even combine checklists with contents pages by using the bottom bar in the editor]

**Comment by BijoySingh** [comment]
Thanks @Wolfram-Wolf for replying :) 
Yes, the app already has Tags which you can use. Click the tag button for filtering out by tags.
