### ISSUE TITLE
Ways to access the app very quickly from anywhere

### ISSUE THREAD

**Issue by Namnodorel** [BijoySingh/Material-Notes-Android-App#35]
Sometimes when you have an idea, you'll want to write it down really fast. Or you suddenly need to take notes on something, but still have to search for and open the notes app. For situations like this, ways to quickly take notes from anywhere would be cool. Possible ways to do that:
- The classic, a widget on the home screen
- A custom quick settings tile (for example NetGuard has this)
- Something on the lock screen? I'm not really sure about this since I don't know how much Android allows apps to meddle with the lockscreen. But it would be great, if possible.

Thank you for creating such an awesome app ^^

**Comment by BijoySingh** [comment]
Hi @Namnodorel thanks for raising this. :)
1. Yes, the widget is in my plan.
2. That is a good idea, I will look into that.
3. Probably lock screen is not that possible, but a sticky notification will be equally good. Will look into that.
