### ISSUE TITLE
Issue with Markdown

### ISSUE THREAD

**Issue by iknownothingaboutcomputers** [BijoySingh/Material-Notes-Android-App#36]
Markdown used in notes don't show up properly in the cards on main page. For e.g, if I bold **github** in a note, then it shows up ** github ** on the main page. It should ideally show up that way only when the note has been opened for editing.

Tried to upload a screenshot but it wouldn't attach for some reason. Sorry.

**Comment by BijoySingh** [comment]
Thanks @iknownothingaboutcomputers I am aware of this issue. Will fix it :)

**Comment by BijoySingh** [comment]
Resolved. Fix will be rolling out with v3.7.9
