### ISSUE TITLE
[Feature request] Number of text lines in preview 

### ISSUE THREAD

**Issue by pilian** [BijoySingh/Material-Notes-Android-App#41]
It would be a great improvemet to set the "Number of text lines in preview" in the settings.
For example, with the number set to "1" there are more notes visible in the main screen.

**Comment by BijoySingh** [comment]
Hi @pilian it was already added in 352dd0031c38cba90480fb62e93b13f2b31beb4c
You can find it in the UI settings in the latest versions of the app.
