### ISSUE TITLE
Dark theme for note creation

### ISSUE THREAD

**Issue by moshpirit** [BijoySingh/Material-Notes-Android-App#6]
First of all, thank you for this great app! Looks awesome! But I'm a dark theme user and I find kind of annoying the creation of the new notes always in white, without the dark theme applied. Would be possible to fix that?

Steps to reproduce:

- Enable the dark mode
- Open the "No notes" message

**Comment by BijoySingh** [comment]
Hi @moshpirit I had detected this bug and I have fixed it in commit 3f845300ca76723ad3f850f9c884f94c9706f3c2

Which means v3.5.0 should have resolved it.

**Comment by moshpirit** [comment]
Cool! Thank you! 👍
