### ISSUE TITLE
Show/Hide format bar button

### ISSUE THREAD

**Issue by moshpirit** [BijoySingh/Material-Notes-Android-App#7]
I think that including a show/hide bar in the upper bar (where the X, colour selection and check symbol are) would be a very comfortable way to include it into other notes (like quick notes)

**Comment by BijoySingh** [comment]
Actually the simple note creation and rich note creation are separate. They are by design, and the format bar cannot be in the simple note creation. 

However, I am adding markdown support right now, which would allow formatting even in the quick note UI.

**Comment by BijoySingh** [comment]
Considering this as resolved, as it is by design.

**Comment by moshpirit** [comment]
I see, well, MarkDown is also awesome so... Thank you!!
