### ISSUE TITLE
Show/Hide keyboard issues

### ISSUE THREAD

**Issue by Jiack214** [BijoySingh/Material-Notes-Android-App#8]
- keyboard should be hidden after the note it's closed.
- keyboard should be shown clicking on "Add a note" buttons.

That's not happening on Android 7 with AOSP keyboard.

**Comment by BijoySingh** [comment]
This should be resolved now. :)

**Comment by Jiack214** [comment]
(Version 3.7)
The same thing happens in the search bar: clicking on back button the keyboard remains open.
